### ISSUE TITLE
[META] Prepare for 1.0 release

### ISSUE THREAD

**Issue by davezych** [github/Scientist.net#51]
I'd like to open a discussion about where we stand right now and where we need to get for an official 1.0 release. 
### Things that are in the ruby lib that we don't have:
- [~~Keeping it clean~~](https://github.com/github/scientist#keeping-it-clean) (implemented by joncloud in #67)
- [~~Enabled~~](https://github.com/github/scientist#ramping-up-experiments) (however this functionality can be done using `RunIf`) (implemented by joncloud in #60)
- [~~Raise on mismatch~~](https://github.com/github/scientist#testing) (for testing purposes) (implemented by joncloud in #53)
- [~~Error handling~~](https://github.com/github/scientist#handling-errors) (implemented by joncloud in #56)

In order to be an _official_ port, these all need to be implemented. 
### Documentation

The docs need to be updated. In my mind we should probably steal the ruby docs and modify the sample code with C# examples. @Haacked - from what I remember this was your intention as well, right? And I'm assuming it's okay if we "steal" the ruby docs, right?
### Testing

I have used Scientist in an app I'm developing and so far haven't run into any issues. This is good. However are we confident in the product and it's stability? I'm not sure how to answer that other than to use it more, and also to wait some time and see if we get any bug reports. 
### Official logo

We need an official logo for the nuget package. I can't really find a logo for the ruby lib that we could mimic and .net-ify. What do we want here?

**Comment by joncloud** [comment]
I should have some time to help port some of the missing features early this week.

**Comment by davezych** [comment]
@joncloud great! If I haven't created issues to track each of the features make sure you create one for whatever you work on so we know it's in the queue.

**Comment by joncloud** [comment]
Will do sounds like a plan.

**Comment by Haacked** [comment]
@davezych This sounds like a great plan! I'm sorry I've been slow to respond. I'm speaking at a conference in Peru and have just been swamped.

**Comment by joncloud** [comment]
@davezych @Haacked what is your opinion on the implementation of [Enabled](https://github.com/github/scientist#ramping-up-experiments)?

It seems like the architecture of C# and Ruby differ enough that this becomes the same as `RunIf` in the C# implementation.  I prepared this implementation (1e1053aea35e3c299cfcc39e86f982f3006c5bb2), but it does not seem to offer much.

**Comment by davezych** [comment]
Yea, `Enabled` is basically a specific case of `RunIf`. I can make a case for both having and not having it.

It'd be nice to have so users can easily distinguish between the operations, it's explicitly shown what's going on, and it following the Ruby lib.

We don't need it because the functionality can be replicated with `RunIf`. 

If I had to choose, I'd say let's put it in because a.) the things I mentioned above and b.) you already did it anyway :smile:

**Comment by davezych** [comment]
Also @joncloud keep rocking it! :guitar:

**Comment by joncloud** [comment]
Should have the remaining core features completed:

Enabled - #60 
Keeping it clean - #67

It looks like the remainder will be `Documentation`, `Testing` and `Logo.

As for the `Logo` it looks like if anything the official ruby library uses :microscope: as seen on the repository's [main page].

[main page]: https://github.com/github/scientist

**Comment by davezych** [comment]
Great job @joncloud. I'll try to find some time to port the documentation over. I'll create an issue to monitor it if I get to it. If you don't see an issue and you want to start that, go ahead.

**Comment by Haacked** [comment]
Forgot to close this issue when we released 1.0! Thanks everyone!
