### ISSUE TITLE
Switch back to .csproj from project.json

### ISSUE THREAD

**Issue by Haacked** [github/Scientist.net#71]
So given [this news](https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/) we should probably switch back.

**Comment by joncloud** [comment]
> The first wave of this change will happen in the Visual Studio “15” RTM

Is there any news on when Visual Studio “15” is scheduled for release?  All I could find is that it is in Preview 2.

**Comment by davezych** [comment]
How great. :smirk: I'll try to find some time to work on this but no guarantees I'll get to it.

**Comment by Haacked** [comment]
> Is there any news on when Visual Studio “15” is scheduled for release? All I could find is that it is in Preview 2.

Nope. We're VSIP partners and we don't know. Just have to look at past schedules to guess but past results are not predictors of future results. :smirk: 

> How great. :smirk: I'll try to find some time to work on this but no guarantees I'll get to it.

Fun times, eh? No guarantees expected. :smile:

**Comment by davezych** [comment]
This announcement is relevant: https://github.com/aspnet/Announcements/issues/205

> As announced by #176 the .NET Execution Environment (DNX) is no longer used by ASP.NET Core and is no longer supported. We will be removing the .NET Version Manager (dnvm) scripts from the https://github.com/aspnet/Home repo on Oct 31, 2016. Please ensure that any infrastructure that is using these scripts has been appropriately updated. We strongly recommend updating your applications to use the latest supported release of .NET Core and ASP.NET Core to ensure that you are running on stable, secure and supported bits.

We have until Nov 28th.

**Comment by joncloud** [comment]
Great catch @davezych.  I think that we might be covered for what aspnet is targeting to update on #61 and #65.  Does that seems to line up?

**Comment by joncloud** [comment]
Is this something we should look at addressing now that VS2017 has a release candidate available for converting from project.json to csproj?

**Comment by Haacked** [comment]
> Is this something we should look at addressing now that VS2017 has a release candidate available for converting from project.json to csproj?

Sure. Want to give it a try?

**Comment by joncloud** [comment]
I'll see if I can find a little time to give it a whirl.  The project isn't very complex so it should be pretty simple.  I think the more complicated part will be the build scripts.

**Comment by davezych** [comment]
If you get that working I can try and find time to update the build scripts however my new job has me super booked.

**Comment by joncloud** [comment]
I made an initial attempt in the branch I referenced above.  The auto-conversion provided by VS2017 failed due to test/Scientist.Test/Scientist.Test.xproj.  I removed that file, and made calls to `dotnet migrate` directly.

Working
* VS2017 can load/compile
* Build script can build/test (note that if you have a local in tests it'll need to be cleared to get the latest preview5)

Not working
* VS2017 test explorer does not list or run any tests
* NuGet packaging - build script manipulates the project.json examining some json properties, and it'll need to be updated to manage xml from the csproj

**Comment by joncloud** [comment]
I just opened up master to look over the `Test Explorer` for reference, and it shows empty.  This was the issue I saw with CSPROJ + VS2017.  Do we have an external dependency that isn't fulfilled with NuGet?

**Comment by Haacked** [comment]
> Do we have an external dependency that isn't fulfilled with NuGet?

Not that I know of. I might be able to look into this next week.

**Comment by Haacked** [comment]
Dons

**Comment by Haacked** [comment]
I meant, Done!
