### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by smarts** [github/Scientist.net#81]
The readme is pretty helpful, but I'm not sure exactly what the difference is [w/o debugging] between `Result<T, TClean>.Candidates` and `Result<T, TClean>.Observations`. Is Observations just Candidates + Control?

**Comment by joncloud** [comment]
`Candidates` doesn't include the control (the observation that comes from `experiment.Use`) observations, and `Observations` includes everything (from `experiment.Use` and `experiment.Try`).

**Comment by joncloud** [comment]
Yup you got it right.

**Comment by smarts** [comment]
Thanks @joncloud
