### ISSUE TITLE
Change root namespace Github to Scientist

### ISSUE THREAD

**Issue by revenger73** [github/Scientist.net#82]
This project has nothing to do with Github itself, so root namespace Github is awkward. Using Scientist.NET in project currently requires the following using

`using Github;`

Change namespace to Scientist, so using in .NET requires the following more logical using statement

`using Scientist;`

**Comment by Haacked** [comment]
The point of namespaces is to avoid conflicts in type names. `Scientist` as a namespace is too generic and could lead to conflicts with others who might have different reasons to write a `Scientist` library. We're not the only scientists, but we are the only GitHub (who happens to sponsor this project).

Just as an example, note that Microsoft does this with their [`Microsoft.Win32`](https://msdn.microsoft.com/en-us/library/microsoft.win32(v=vs.110).aspx) namespace. It's pretty common to have the company name be the root namespace of a library to help ensure conflict avoidance.
